import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { fetchTools } from '@/lib/api'
import { Drawer } from '@/components/ui/Drawer'
import { JsonBlock } from '@/components/ui/JsonBlock'
import { SkeletonTable } from '@/components/ui/SkeletonTable'
import type { Tool } from '@/types'
import { zh } from '@/lib/utils'

export function Catalog() {
  const query = useQuery({ queryKey: ['tools'], queryFn: () => fetchTools() })
  const [selected, setSelected] = useState<Tool | null>(null)
  const [status, setStatus] = useState<'all' | 'accepted' | 'rejected'>('accepted')
  const [risk, setRisk] = useState('all')
  const rows = useMemo(() => (query.data ?? []).filter((tool) => (status === 'all' || tool.accepted === (status === 'accepted')) && (risk === 'all' || tool.governance.riskLevel === risk)), [query.data, status, risk])
  return <div className="page-shell"><header className="border-b border-line pb-5"><h1 className="page-title">语义工具目录</h1><p className="page-description">标准 MCP 工具与 GateForge 治理元数据分开存储和展示。</p></header><div className="flex flex-wrap gap-3"><select className="input" value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="accepted">可用工具</option><option value="rejected">已过滤 API</option><option value="all">全部</option></select><select className="input" value={risk} onChange={(e) => setRisk(e.target.value)}><option value="all">全部风险</option><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option><option value="critical">严重风险</option></select><span className="ml-auto self-center font-mono text-xs text-ink-faint">{rows.length} 个工具</span></div>{query.isLoading ? <SkeletonTable rows={8} /> : <div className="overflow-x-auto rounded-lg border border-line bg-surface"><table className="w-full min-w-[960px] text-sm"><thead className="bg-[#f8fafc] text-left text-xs text-ink-muted"><tr><th className="px-4 py-3">MCP 工具</th><th>API</th><th>领域 / 意图</th><th>影响</th><th>风险与审批</th><th>质量</th></tr></thead><tbody>{rows.map((tool) => <tr key={tool.id} className="cursor-pointer border-t border-line hover:bg-brand-tint" onClick={() => setSelected(tool)}><td className="px-4 py-3"><code className="font-mono text-xs font-semibold">{tool.standard.name}</code><p className="mt-1 max-w-md truncate text-xs text-ink-faint">{tool.standard.description}</p>{!tool.accepted && <span className="text-[11px] text-block">{tool.rejection_reasons.map(zh).join('、')}</span>}</td><td><span className="font-mono text-xs">{tool.method} {tool.path}</span><div className="text-[11px] text-ink-faint">{tool.source_name}</div></td><td><div>{tool.governance.domain.map(zh).join(' / ')}</div><div className="text-xs text-ink-faint">{tool.governance.intent.map(zh).join(' / ')}</div></td><td><span className={`rounded-full px-2 py-1 text-xs ${tool.governance.destructive ? 'bg-[var(--block-tint)] text-block' : tool.governance.write ? 'bg-[var(--warn-tint)] text-warn' : 'bg-[var(--pass-tint)] text-pass'}`}>{tool.governance.destructive ? '破坏性' : tool.governance.write ? '写入' : '只读'}</span></td><td><strong className={tool.governance.riskLevel === 'low' ? 'text-pass' : 'text-warn'}>{zh(tool.governance.riskLevel)}风险</strong><div className="text-[11px] text-ink-faint">{tool.governance.approvalRequired ? `需要审批 · ${zh(tool.governance.approvalRole)}` : '无需审批'}</div></td><td><span className="font-mono">{Math.round(tool.governance.qualityScore * 100)}%</span></td></tr>)}</tbody></table></div>}
    <Drawer open={!!selected} onClose={() => setSelected(null)} title={selected?.standard.name ?? '工具'} width={720}>{selected && <div className="space-y-4"><div className="rounded-lg bg-brand-tint p-4 text-sm leading-6">{selected.standard.description}</div><JsonBlock title="标准 MCP 工具" data={selected.standard} /><JsonBlock title="GateForge 治理附加信息" data={selected.governance} /><JsonBlock title="后端 API 映射" data={selected.backend_mapping} /></div>}</Drawer>
  </div>
}
