import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { fetchSources, importSource, ApiError } from '@/lib/api'
import { Button } from '@/components/ui/Button'
import { ErrorState } from '@/components/ui/ErrorState'
import { useToast } from '@/components/ui/Toast'
import { formatDate, shortHash, zh } from '@/lib/utils'

export function Intake() {
  const client = useQueryClient(); const toast = useToast()
  const sources = useQuery({ queryKey: ['sources'], queryFn: fetchSources })
  const [form, setForm] = useState({ name: '', slug: '', spec_url: '', spec_text: '', base_url: '', environment: 'test', owner: '' })
  const mutation = useMutation({ mutationFn: importSource, onSuccess: async (source) => { await client.invalidateQueries(); toast(`已分析 ${source.operation_count} 个 API，保留 ${source.accepted_count} 个工具`); setForm({ name: '', slug: '', spec_url: '', spec_text: '', base_url: '', environment: 'test', owner: '' }) } })
  const error = mutation.error as ApiError | null
  const set = (key: keyof typeof form, value: string) => setForm((v) => ({ ...v, [key]: value }))
  return <div className="page-shell"><header className="border-b border-line pb-5"><h1 className="page-title">API 接入与分析</h1><p className="page-description">批量入口支持后端 API；当前工作台导入单份 OpenAPI/Swagger，并自动过滤重复、废弃与运行探针接口。</p></header>
    <div className="grid items-start gap-5 xl:grid-cols-[420px_1fr]"><section className="panel p-5"><h2 className="font-semibold">导入 API 来源</h2><div className="mt-4 space-y-3"><Field label="来源名称"><input className="input w-full" value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="订单系统" /></Field><div className="grid grid-cols-2 gap-3"><Field label="来源标识"><input className="input w-full font-mono" value={form.slug} onChange={(e) => set('slug', e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ''))} placeholder="orders" /></Field><Field label="负责人"><input className="input w-full" value={form.owner} onChange={(e) => set('owner', e.target.value)} placeholder="商业平台团队" /></Field></div><Field label="OpenAPI 地址"><input className="input w-full font-mono text-xs" value={form.spec_url} onChange={(e) => { set('spec_url', e.target.value); if (e.target.value) set('spec_text', '') }} placeholder="https://api.example.com/openapi.json" /></Field><div className="text-center text-xs text-ink-faint">或上传 JSON / YAML</div><Field label="OpenAPI 文件"><input type="file" accept=".json,.yaml,.yml" className="text-xs" onChange={async (e) => { const f = e.target.files?.[0]; if (f) { set('spec_text', await f.text()); set('spec_url', '') } }} />{form.spec_text && <span className="text-xs text-pass">已读取 {form.spec_text.length.toLocaleString()} 字符</span>}</Field><Field label="基础地址（规范未声明服务地址时）"><input className="input w-full font-mono text-xs" value={form.base_url} onChange={(e) => set('base_url', e.target.value)} placeholder="https://api.example.com" /></Field><Field label="环境"><select className="input w-full" value={form.environment} onChange={(e) => set('environment', e.target.value)}><option value="test">测试</option><option value="staging">预发布</option><option value="prod">生产</option></select></Field>{error && <ErrorState compact what={error.what} fix={error.fix} />}<Button variant="primary" className="w-full" disabled={!form.name.trim() || !(form.spec_url || form.spec_text) || mutation.isPending} onClick={() => mutation.mutate({ ...form, slug: form.slug || undefined, spec_url: form.spec_url || undefined, spec_text: form.spec_text || undefined, base_url: form.base_url || undefined })}>{mutation.isPending ? '解析、分析与富化中…' : '分析 API'}</Button></div></section>
      <section className="panel overflow-hidden"><header className="border-b border-line px-5 py-4"><h2 className="font-semibold">已接入来源</h2><p className="text-xs text-ink-faint">GateForge 保存输入与工程化结果，不承担来源服务发现</p></header>{(sources.data ?? []).map((s) => <div key={s.id} className="grid grid-cols-[1fr_auto] gap-4 border-b border-line px-5 py-4 last:border-0"><div><div className="flex items-center gap-2"><span className="font-medium">{s.name}</span><code className="rounded bg-surface-subtle px-1.5 text-[10px] text-ink-muted">{zh(s.environment)}</code></div><div className="mt-1 font-mono text-[11px] text-ink-faint">{s.base_url} · {shortHash(s.spec_hash)}</div><div className="mt-1 text-xs text-ink-muted">负责人：{zh(s.owner)} · {formatDate(s.imported_at)}</div></div><div className="text-right"><div className="font-mono text-lg font-semibold">{s.accepted_count}/{s.operation_count}</div><div className="text-[11px] text-ink-faint">可用工具</div>{s.rejected_count > 0 && <div className="text-[11px] text-warn">过滤 {s.rejected_count}</div>}</div></div>)}{!sources.data?.length && <p className="p-10 text-center text-sm text-ink-muted">尚未导入 API。</p>}</section></div>
  </div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-1.5"><span className="text-xs font-medium text-ink-muted">{label}</span>{children}</label> }
