import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { fetchPacks } from '@/lib/api'
import { formatDate, shortHash, zh } from '@/lib/utils'

export function Packs() {
  const query = useQuery({ queryKey: ['packs'], queryFn: fetchPacks })
  return <div className="page-shell"><header className="flex items-end justify-between border-b border-line pb-5"><div><h1 className="page-title">MCP 能力包构建产物</h1><p className="page-description">每次构建都会产生包含能力图、治理信息、测试证据和构建清单的不可变工程产物。</p></div><Link to="/" className="text-sm font-medium text-brand-strong">按目标描述构建 →</Link></header><div className="grid gap-4 lg:grid-cols-2">{(query.data ?? []).map((pack) => <Link key={pack.id} to={`/packs/${pack.id}`} className="panel p-5 hover:border-brand"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{pack.name}</h2><code className="text-[11px] text-ink-faint">{pack.mcp_server.name as string}</code></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${pack.status === 'ready' ? 'bg-[var(--pass-tint)] text-pass' : 'bg-[var(--block-tint)] text-block'}`}>{zh(pack.status)}</span></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink-muted">{pack.description}</p><div className="mt-5 grid grid-cols-4 border-t border-line pt-4 text-xs"><div><strong className="font-mono text-base text-ink">{pack.capability_graphs?.length ?? 0}</strong><div className="text-ink-faint">能力图</div></div><div><strong className="font-mono text-base text-ink">{pack.tools.length}</strong><div className="text-ink-faint">原子工具</div></div><div><strong className="font-mono text-base text-ink">{Math.round(pack.test_report.quality_score * 100)}%</strong><div className="text-ink-faint">质量分</div></div><div><strong className="font-mono text-base text-ink">{pack.test_report.blocking_failures}</strong><div className="text-ink-faint">阻断项</div></div></div><div className="mt-3 flex justify-between font-mono text-[10px] text-ink-faint"><span>{shortHash(pack.artifact_hash)}</span><span>{formatDate(pack.created_at)}</span></div></Link>)}</div>{!query.data?.length && <div className="panel p-12 text-center text-sm text-ink-muted">还没有构建产物。</div>}</div>
}
